apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: social-log-pvc
  annotations:
    v8tix.com/created-by: "V8TIX"
    v8tix.com/mail: "info@v8tix.com"
    v8tix.com/app: "Katix"
    v8tix.com/app-tier: "Back-end"
    v8tix.com/environment: "Development"
    v8tix.com/release: "Canary"
    v8tix.com/tenant: "None"
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce