apiVersion: v1
kind: Service
metadata:
  name: social-np
  namespace: social-ns
  annotations:
    v8tix.com/created-by: "V8TIX"
    v8tix.com/mail: "info@v8tix.com"
    v8tix.com/app: "Katix"
    v8tix.com/app-tier: "Back-end"
    v8tix.com/environment: "Development"
    v8tix.com/release: "Canary"
    v8tix.com/tenant: "None"
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30123
  selector:
    app: social