# Bind the ClusterRole to the desired set of service accounts.
# Policies should typically be bound to service accounts in a namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: social-rb
  namespace: social-ns
  annotations:
    v8tix.com/created-by: "V8TIX"
    v8tix.com/mail: "info@v8tix.com"
    v8tix.com/app: "Katix"
    v8tix.com/app-tier: "Back-end"
    v8tix.com/environment: "Development"
    v8tix.com/release: "Canary"
    v8tix.com/tenant: "None"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: social-cr
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts