apiVersion: v1
kind: ResourceQuota
metadata:
  name: social-objects
  namespace: social-ns
  annotations:
    v8tix.com/created-by: "V8TIX"
    v8tix.com/mail: "info@v8tix.com"
    v8tix.com/app: "Katix"
    v8tix.com/app-tier: "Back-end"
    v8tix.com/environment: "Development"
    v8tix.com/release: "Canary"
    v8tix.com/tenant: "None"
spec:
  hard:
    pods: 3
    replicationcontrollers: 0
    secrets: 8
    configmaps: 0
    persistentvolumeclaims: 4
    services: 1
    services.loadbalancers: 0
    services.nodeports: 1
    ssd.storageclass.storage.k8s.io/persistentvolumeclaims: 2