apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: default
  annotations:
    v8tix.com/created-by: "V8TIX"
    v8tix.com/mail: "info@v8tix.com"
    v8tix.com/app: "Katix"
    v8tix.com/app-tier: "Back-end"
    v8tix.com/environment: "Development"
    v8tix.com/release: "Canary"
    v8tix.com/tenant: "None"
spec:
  allowedCapabilities:
    - SYS_TIME
  defaultAddCapabilities:
    - CHOWN
  requiredDropCapabilities:
    - SYS_ADMIN
    - SYS_MODULE
  hostIPC: false
  hostPID: false
  hostNetwork: false
  hostPorts:
    - min: 10000
      max: 11000
    - min: 13000
      max: 14000
  privileged: false
  readOnlyRootFilesystem: true
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: 2020
        max: 2020
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 2020
        max: 2020
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 2020
        max: 2020
  seLinux:
    rule: RunAsAny
  volumes:
    - '*'