kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: social-cr
  annotations:
    v8tix.com/created-by: "V8TIX"
    v8tix.com/mail: "info@v8tix.com"
    v8tix.com/app: "Katix"
    v8tix.com/app-tier: "Back-end"
    v8tix.com/environment: "Development"
    v8tix.com/release: "Canary"
    v8tix.com/tenant: "None"
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - default
    verbs:
      - use